name: Deployment Pipeline

on:
  push:
    branches:
      - main  # Triggers when changes are merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/hng12-devbot-fastapi-book-project 
            git pull origin main
            source venv/bin/activate  # Ensure venv is activated if used
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
